clone_base:
  image: docker:git
  services:
    - docker:dind
  script:
    - docker pull photon:1.0
    - docker tag photon:1.0 registry.gitlab.com/gbraad/photon:1.0
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/gbraad/photon:1.0
  only:
    - master


build_base:
  image: docker:git
  services:
    - docker:dind
  script:
    - git clone https://github.com/vmware/photon.git photon --depth 1 -b master
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/photon:build ./photon
    - docker push registry.gitlab.com/gbraad/photon:build
  only:
    - master
  when: manual
